/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e02f5c2a4f4b55911b4514b
*
* You will get 10% discount for each one of your friends
* 
*/
// Import Libraries
import { Component, OnInit } from '@angular/core';
import { Location } from '@angular/common';
import { ActivatedRoute } from '@angular/router';
// Import Services
import { GlobalSettingService } from '../../services/global-setting.service';
// Import Models
import { GlobalSetting } from '../../domain/midas_db/global-setting';

// START - USED SERVICES
/**
* GlobalSettingService.create
*	@description CRUD ACTION create
*
* GlobalSettingService.get
*	@description CRUD ACTION get
*	@param ObjectId id Id resource
*
* GlobalSettingService.update
*	@description CRUD ACTION update
*	@param ObjectId id Id
*
*/
// END - USED SERVICES

/**
 * This component allows to edit a GlobalSetting
 */
@Component({
    selector: 'app-global-setting-edit',
    templateUrl: 'global-setting-edit.component.html',
    styleUrls: ['global-setting-edit.component.css']
})
export class GlobalSettingEditComponent implements OnInit {
    item: GlobalSetting;
    model: GlobalSetting;
    formValid: Boolean;

    constructor(
    private globalsettingService: GlobalSettingService,
    private route: ActivatedRoute,
    private location: Location) {
        // Init item
        this.item = new GlobalSetting();
    }

    /**
     * Init
     */
    ngOnInit() {
        this.route.params.subscribe(param => {
            const id: string = param['id'];
            if (id !== 'new') {
                this.globalsettingService.get(id).subscribe(item => this.item = item);
            }
            // Get relations
        });
    }


    /**
     * Save GlobalSetting
     *
     * @param {boolean} formValid Form validity check
     * @param GlobalSetting item GlobalSetting to save
     */
    save(formValid: boolean, item: GlobalSetting): void {
        this.formValid = formValid;
        if (formValid) {
            if (item._id) {
                this.globalsettingService.update(item).subscribe(data => this.goBack());
            } else {
                this.globalsettingService.create(item).subscribe(data => this.goBack());
            } 
        }
    }

    /**
     * Go Back
     */
    goBack(): void {
        this.location.back();
    }


}



