/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e02f5c2a4f4b55911b4514b
*
* You will get 10% discount for each one of your friends
* 
*/
import { Component } from '@angular/core';
import { OnInit } from '@angular/core';
// Import Services
import { GlobalSettingService } from '../../services/global-setting.service';
// Import Models
import { GlobalSetting } from '../../domain/midas_db/global-setting';

// START - USED SERVICES
/**
* GlobalSettingService.delete
*	@description CRUD ACTION delete
*	@param ObjectId id Id
*
* GlobalSettingService.list
*	@description CRUD ACTION list
*
*/
// END - USED SERVICES

/**
 * This component shows a list of GlobalSetting
 * @class GlobalSettingListComponent
 */
@Component({
    selector: 'app-global-setting-list',
    templateUrl: './global-setting-list.component.html',
    styleUrls: ['./global-setting-list.component.css']
})
export class GlobalSettingListComponent implements OnInit {
    list: GlobalSetting[];
    search: any = {};
    idSelected: string;
    constructor(
        private globalsettingService: GlobalSettingService,
    ) { }

    /**
     * Init
     */
    ngOnInit(): void {
        this.globalsettingService.list().subscribe(list => this.list = list);
    }

    /**
     * Select GlobalSetting to remove
     *
     * @param {string} id Id of the GlobalSetting to remove
     */
    selectId(id: string) {
        this.idSelected = id;
    }

    /**
     * Remove selected GlobalSetting
     */
    deleteItem() {
        this.globalsettingService.remove(this.idSelected).subscribe(data => this.list = this.list.filter(el => el._id !== this.idSelected));
    }

}
